name: Update tvl 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest kcc tvl
        run: |
          curl --request GET \
          --url 'https://ksf-tvl.herokuapp.com/api/tvl/kcc''
